version: '2'
services:
  buoy:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mqtt
    restart: on-failure
    networks:
      - mqtt
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - mosquitto:/mosquitto
      - ./contrib/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt
networks:
  mqtt:
volumes:
  mosquitto:
